#version: "3.10"

services:
  api:
    build: .
    container_name: my_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./api_data/:/app_data/
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend_net

  db:
    image: postgres:16 # This is the official Postgres image from Docker Hub
    # The `container_name` tag allows us to give a name to our container.
    container_name: postgres_db # This is the name of the container
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    restart: always
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # The `volumes` tag allows us to share a folder with our container
    # Its syntax is as follows: [folder path on our machine]:[folder path to retrieve in the container]
    volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL da>
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`
      # You don't need to create the `db-data` folder. Docker Compose will do it for you
      - ./pgdata/:/var/lib/postgresql/data/
    networks: # This allows us to connect the container to a specific network
      - backend_net
      

  redis:
    image: redis:7
    container_name: redis_cache
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./redis_data/:/data/
    networks:
      - backend_net
    ports:
      - "6379:6379"

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
  app:
    driver: local

networks:
  backend_net:
    driver: bridge

